version: '3'

services:
  drand:
    image: angelocapossele/drand:latest
    volumes:
      - ./data:/root/.drand
    ports:
      - "0.0.0.0:1234:8080"
    entrypoint: drand 
    command: --verbose 2 start --listen 127.0.0.1:8080 --tls-disable
    restart: always